#!/bin/sh
### BEGIN INIT INFO
# Provides:          startct
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Chess Test
# Description:       Start Chess Test
### END INIT INFO
/home/christian/chesstest/start
